# Generated by Django 4.2.7 on 2026-05-21 12:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(default=accounts.models.generate_otp, max_length=6),
        ),
    ]
